### ISSUE TITLE
[feature] 刷天启碎片改进

### ISSUE THREAD

**Issue by pandacase** [overflow65537/MAA_SnowBreak#12]
当前天启碎片只能刷设置一个角色进行刷取，即单纯为了达成每日任务的条件。但是每天的材料至少可以刷两个角色，同时每个版本会固定发放14\*2\*3个天启体力补充（材料实际名称忘了，不过应该能看懂）。

希望改进为：设置一个角色队列，其实队首的两个角色在每天都会进行刷取，然后若队列大小>2，即存在第三个甚至更多角色，则会检查当前是否存在限时的天启体力，若有则依次完成以下操作直到队列为空：
1. 每次消耗2个限时天启材料
2. 刷取对应角色天启

**Comment by overflow65537** [comment]
你用的应该是图形化操作界面吧
在任务栏的右上角有一个加号，可以添加任务

现在的刷碎片任务默认会使用记忆嵌片包
并且在没有次数/没有记忆嵌片包/没有记忆嵌片的时候停止任务

所以你想刷那个任务就添加上就可以了，甚至可以提前添加三个刷碎片任务，这样版本更新的时候也就不用再次添加了

**Comment by pandacase** [comment]
sorry，才发现上面有一行管理图标。（原本用 [SRC](https://github.com/LmeSzinc/StarRailCopilot) 过来的，应用逻辑不太一样 先入为主了）

或许可以把 GUI 的图标调大，并且颜色换深一点

thanks. : )
