### ISSUE TITLE
模拟器兼容性

### ISSUE THREAD

**Issue by chesha1** [overflow65537/MAA_SnowBreak#4]
有什么推荐的安卓模拟器吗？我试了如下几个都不行

- 雷电：尘白本体检测到模拟器不运行
- mumu：网络异常
- 蓝叠：尘白本体检测到模拟器不运行
- 夜神：不支持和 hyper-v 共存

**Comment by overflow65537** [comment]
应该是只有mumu模拟器能运行

**Comment by UVJkiNTQ** [comment]
mumu12也提示模拟器不能运行了，请问目前还有能用的模拟器吗

**Comment by overflow65537** [comment]
> mumu12也提示模拟器不能运行了，请问目前还有能用的模拟器吗

你应是b服的吗，b服的一直不能运行
如果是官服的，不太明白是什么问题导致的。重装一下mumu试试能不能解决
或者，我把pc版的任务做好了，在releases。但某些识别区域可能不太准确，有问题可以发issue
