### ISSUE TITLE
希望作者更新的地方

### ISSUE THREAD

**Issue by snowly233** [overflow65537/MAA_SnowBreak#5]
1、把新版本新角色的个人故事碎片可以增加一下，比如这个版本的大金鱼
2、体力使用不会将金色体力药自动使用，而邮件里面时不时会发放限时金色体力药，希望也能够自动将其使用了

**Comment by overflow65537** [comment]
1大金鱼已经加上了
2这个可以考虑

**Comment by overflow65537** [comment]
完成,但缺少测试
我没有体力药了

**Comment by snowly233** [comment]
> 完成,但缺少测试 我没有体力药了

你虽然在github上更新了。。但是release没更新，我也没clone你的项目。。。有没有考虑做个自动更新QWQ

**Comment by overflow65537** [comment]
> > 完成,但缺少测试 我没有体力药了
> 
> 你虽然在github上更新了。。但是release没更新，我也没clone你的项目。。。有没有考虑做个自动更新QWQ

我刚才想和Pc端一起更新来这
写着写着发现pc端不太好写
现在更新上了

**Comment by overflow65537** [comment]
> > 完成,但缺少测试 我没有体力药了
> 
> 你虽然在github上更新了。。但是release没更新，我也没clone你的项目。。。有没有考虑做个自动更新QWQ

我刚才想和Pc端一起更新来这
写着写着发现pc端不太好写
现在更新上了

**Comment by snowly233** [comment]
> 完成,但缺少测试 我没有体力药了

我测了，用不了，好像是点了右边的那个倒计时那边了，并没点金色的体力药

**Comment by overflow65537** [comment]
> > 完成,但缺少测试 我没有体力药了
> 
> 我测了，用不了，好像是点了右边的那个倒计时那边了，并没点金色的体力药

你的体力药还剩几天，我这边调的3天内的才会使用

**Comment by overflow65537** [comment]
> > 完成,但缺少测试 我没有体力药了
> 
> 我测了，用不了，好像是点了右边的那个倒计时那边了，并没点金色的体力药

你可以去/resource/base/pipeline/战斗.json里面搜索3天
然后后面加上4天5天6天之类的在保存测试下看看

**Comment by snowly233** [comment]
之前克隆了你的仓库，想着fetch之后直接merge再用install再解压一次。。。结果版本还是更新不了。。。。是什么问题啊

**Comment by snowly233** [comment]
破案了，1.0.6还是会卡体力药

**Comment by overflow65537** [comment]
> 破案了，1.0.6还是会卡体力药

你卡在什么界面了？
我刚才把OCR结果改成了无时间限制
程序正常运行
能不能是战斗次数选项或者是刷完全部体力的选项出问题了

**Comment by overflow65537** [comment]
> 破案了，1.0.6还是会卡体力药

找到了个问题，活动战斗任务会在选择完抓取次数后就跳转到常规战斗的任务中了
但我感觉这个应该不是问题，毕竟活动战斗和常规战斗后半部分的处理一模一样。
我现在把活动战斗和常规战斗放一起了
用无限制的橙色体力药试了一下
每出什么问题
你现在再看看
