### ISSUE TITLE
2.0版本催更

### ISSUE THREAD

**Issue by snowly233** [overflow65537/MAA_SnowBreak#7]
我来催更了XD
这次ui更新量有点大，图片应该全部都需要更换

**Comment by snowly233** [comment]
另外提个建议，活动任务左下角处有一个全部领取按钮，可以使用那个来领取任务奖励，上版本的活动任务用脚本我好像就没领到过

**Comment by overflow65537** [comment]
已经更了
关于第二个问题,我一直没注意,而且我一直是用的全部领取,只不过用的OCR
不过这个版本我改成图片识别了,再看看有什么问题吧

**Comment by snowly233** [comment]
呃，邮件和商店会出现卡住的问题，需要手动点才能进该页面

**Comment by snowly233** [comment]
[maa.log](https://github.com/user-attachments/files/16197092/maa.log)

**Comment by overflow65537** [comment]
> [maa.log](https://github.com/user-attachments/files/16197092/maa.log)
> 

改界面的时候忘了这俩了
现在应该没问题了

**Comment by snowly233** [comment]
> > [maa.log](https://github.com/user-attachments/files/16197092/maa.log)
> 
> 改界面的时候忘了这俩了 现在应该没问题了

商店邮件有没有问题我不知道，但是嵌片包卡住用不了

**Comment by snowly233** [comment]
[maa.log](https://github.com/user-attachments/files/16202283/maa.log)
目前测试下来，因为记忆嵌片包卡住，邮件和商店没办法用我不知道是不是因为嵌片的原因，然后活动任务是直接都还没点活动任务那个按钮直接就结束下一步的，可能活动任务这个等待时间还得稍微拉长一些，活动ui过场动画稍微有点长

**Comment by overflow65537** [comment]
> [maa.log](https://github.com/user-attachments/files/16202283/maa.log)
> 目前测试下来，因为记忆嵌片包卡住，邮件和商店没办法用我不知道是不是因为嵌片的原因，然后活动任务是直接都还没点活动任务那个按钮直接就结束下一步的，可能活动任务这个等待时间还得稍微拉长一些，活动ui过场动画稍微有点长

记忆嵌片卡住是因为识别目标写错了，昨天我嵌片包用完了，就没测试，现在好了
活动任务确实像你说的一样，动画时间太长，而活动任务的任务链还没有活动战斗长，所以直接就进行到返回主菜单那一步了，现在增加了两秒延迟

**Comment by snowly233** [comment]
> > [maa.log](https://github.com/user-attachments/files/16202283/maa.log)
> > 目前测试下来，因为记忆嵌片包卡住，邮件和商店没办法用我不知道是不是因为嵌片的原因，然后活动任务是直接都还没点活动任务那个按钮直接就结束下一步的，可能活动任务这个等待时间还得稍微拉长一些，活动ui过场动画稍微有点长
> 
> 记忆嵌片卡住是因为识别目标写错了，昨天我嵌片包用完了，就没测试，现在好了 活动任务确实像你说的一样，动画时间太长，而活动任务的任务链还没有活动战斗长，所以直接就进行到返回主菜单那一步了，现在增加了两秒延迟

1.1.2.1现在运行不了。直接报错了

**Comment by snowly233** [comment]
1.1.2刷碎片会多出来一次使用，要我说逻辑应该可以这么做：
刷碎片首先给每个角色设定一个每日的全局值，每天只要有一次成功刷取碎片默认今天已经刷取成功，不再进入该流程
碎片默认max2次一起刷了，使用6点
第一步ocr先识别右上角数字是不是等于6或12，，不是的话那就是0，补充嵌片包直到识别右上角等于6，在进入刷取流程

**Comment by snowly233** [comment]
哦对了，凭证的限定奖励领取应该是识别不出来的，虽然说没什么所谓可以手动领，但脚本确实不会自动领取

**Comment by overflow65537** [comment]
> 哦对了，凭证的限定奖励领取应该是识别不出来的，虽然说没什么所谓可以手动领，但脚本确实不会自动领取
> 

对，那个没有过期时间，我当时就没写
晚上就给加上

**Comment by snowly233** [comment]
1.1.3版本完美运行，perfect，牛的
