### ISSUE TITLE
刷天启碎片，一些角色无法定位

### ISSUE THREAD

**Issue by ChuxiaRenwu** [overflow65537/MAA_SnowBreak#8]
我s角色少，用下来有问题的是凯姐，进入刷天启的页面，向左滑动后无法继续点击，而且cpu占用大幅增加，过一段时间继续后续任务，但模拟器内游戏还卡在凯姐刷天启任务的界面

**Comment by ChuxiaRenwu** [comment]
使用mumu模拟器，分辨率为1280X720

**Comment by overflow65537** [comment]
这就是个悲伤的故事了,我没抽到凯西娅:(
你把在个人故事里凯西娅的图片用mumu的截图(F9键)发给我
1920*1080和1280*720都需要一张,我改一下
(最好你其他的S级人物也发一遍)

**Comment by overflow65537** [comment]
![屏幕截图 2024-08-05 184958](https://github.com/user-attachments/assets/e3a304a2-6c16-45d3-9ebe-5f84b35d5f6f)
像是这种

不过我刚才试了一下,进入刷凯西娅碎片没问题,你应该是卡在行为02那边了把
如果是的话,那就在发一张凯西娅行为02的图片,只需要进去就行,不需要拖动之类的操作.我怀疑是凯西娅的行为02位置和别人不一样
